name: ESHM20 Testing
authors:
  - Pablo Iturrieta
  - José A. Bayona
  - Maximilian J. Werner
  - Fabrice Cotton
  - Graeme Weatherill
  - Laurentiu Danciu
catalog_doi: 10.5880/GFZ.EMEC.2021.001
catalog_provider: GFZ
floatcsep_version: v0.5.1
pycsep_version: v0.8.0
last_run: 2026-07-11T15:02:54
exp_time: Pseudo-Prospective / Prospective
license: CC BY 4.0

time_config:
  start_date: 2015-1-1T00:00:00
  end_date: 2022-1-1T00:00:00

region_config:
  region: region_europe.txt
  mag_min: 4.9
  mag_max: 8.9
  mag_bin: 0.2
  depth_min: -2
  depth_max: 70

catalog: emec_catalog.json
model_config: models.yml
test_config: tests.yml

postprocess:
  plot_forecasts:
    basemap: ESRI_terrain
    plot_region: False
    colorbar_labelsize: 14
    colorbar_ticksize: 12
    alpha_exp: 0.8
    catalog:
      plot_region: False
      legend: True
      legend_loc: 1
      legend_fontsize: 14
      legend_titlesize: 16
      markersize: 6
      markercolor: blue
  plot_catalog:
    figsize: [12,8]
    plot_region: False
    legend: True
    legend_loc: 1
    legend_fontsize: 14
    legend_titlesize: 16
    markersize: 6
    markercolor: blue
